version: "3.8"

services:
  web:
    container_name: web
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    # depends_on:
    #   - db
    command: bash -c "
      uvicorn main:app
      --host 0.0.0.0 --port 80
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload"
    environment:
      APP: "main:app"
      SECRET_KEY: "12345"

      DB_NAME: "exac"
      DB_HOST: "localhost"
      DB_PORT: 27017
  
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./nginx/Dockerfile
  #   ports:
  #     - 80:80
  #   command: ["nginx", "-g", "daemon off;"]
  #   depends_on:
  #     - web

  # db:
  #   container_name: db
  #   image: mongo
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_DATABASE: exac
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data/
  #   ports:
  #     - 27017:27017
  #   command: mongod --quiet --logpath /dev/null

# volumes:
#   dbdata: null
#   cache:
#     driver: local
